import type { Metadata } from "next";
import "../globals.css";
import { CartProvider } from "@/store/CartProvider";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
    <body>
      
     
      <CartProvider>
      <Header />
    {children}
      </CartProvider>
     
      </body>
  </html>
    
     
     
  );
}
