import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { CartProvider } from "@/store/CartProvider";
import Header from "@/components/Header";
import { SessionProvider } from "next-auth/react"
import CartCount from "@/components/CartCount";
import HeroSlider from "@/components/Hero2"
const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de">
    <body>
      
     
      <CartProvider>
      <Header />
    {children}
      </CartProvider>
     
      </body>
  </html>
    
     
     
  );
}
